[package]
name = "drone"
version = "0.1.0"
edition = "2021"

[net]
git-fetch-with-cli = true

[dependencies]
crossbeam = "0.8.4"
wg_internal = { git = "https://git@github.com/Rusteze-AP/RS_WGL_2024.git", branch = "main"}

[lib]
name = "drone"
path = "src/lib.rs"
