[package]
name = "rusteze_drone"
version = "0.1.0"
edition = "2021"

[net]
git-fetch-with-cli = true

[dependencies]
crossbeam = "0.8.4"
wg_internal = { git = "https://github.com/Rusteze-AP/RS_WGL_2024", branch = "sim_controller_changes" }

[lib]
name = "rusteze_drone"
path = "src/lib.rs"