name: Cargo Build & Test

on:
  push:
    branches:
      - main
  pull_request:
  
env:
  CARGO_TERM_COLOR: always

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Test
      run: cargo test --verbose --no-fail-fast --color always
